spring:
  application:
    name: NexaMart

  datasource:
    url: jdbc:mysql://localhost:3306/NexaMart
    username: root
    password: Bhushan@007
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5454
