package com.nexamart.domain;

public enum AccountStatus {
	
	PENDING_VERIFICATION, // ACCOUNT CREATED BIT NOT VERIFIED
	ACTIVE, // ACCOUNT IS ACTIVE AND IN GOOD STAND
	SUSPENDED, // TEMP SUSPENDED DUE TO VIOLATION
	DEACTIVATED, // USER DEACTIAVTE ACCOUNT
	BANNED, // VIOLATION OF ACCOUNT
	CLOSED // PERMENTLY CLOSED 
	

}
